### ISSUE TITLE
Fixed 2 errors in get_time.lua and luajit_options.lua but got third error - luajit: not enough memory

### ISSUE THREAD

**Issue by JohnClaw** [CapsAdmin/luajit-llama3#2]
I compiled latest luajit binaries with MS Visual Studio 2022. Then i tried to launch your script like this: luajit.exe llama.lua lua "Meta-Llama-3-8B-Instruct-Q4_0.gguf" "write a luajit haiku".

It caused first error:

```
luajit: .\debug\luajit_options.lua:128: unknown or malformed optimization flag 'sizemcode=true'
stack traceback:
        [C]: in function 'start'
        .\debug\luajit_options.lua:128: in function 'Set'
        .\debug\luajit_options.lua:133: in function 'SetOptimized'
        llama.lua:2: in main chunk
        [C]: at 0x00402020
```

I used Deepseek Deepthink (https://chat.deepseek.com/) to fix problem in luajit_options.lua. Then i tried to launch your script again and got second error:

```
luajit: .\debug\get_time.lua:33: cannot resolve symbol 'clock_gettime': The specified procedure could not be found.

stack traceback:
        [C]: in function '__index'
        .\debug\get_time.lua:33: in main chunk
        [C]: in function 'require'
        llama.lua:4: in main chunk
        [C]: at 0x00843200
```

I asked Deepthink to solve the issue and "he" managed to do it. I tried to launch your script in third time and got new error:

`luajit: not enough memory`

How much ram should i have to run your script? Is 16gb ram not enough?

**Comment by JohnClaw** [comment]
I attached fixed get_time.lua and fixed luajit_option.lua in zip archive.
[fixed_scripts.zip](https://github.com/user-attachments/files/18240865/fixed_scripts.zip)

**Comment by CapsAdmin** [comment]
Thanks, I've fixed both of those errors now. As for distribution, use luajit 2.1 with gc64 enabled (should be the default as of late). Maybe the 32bit gc is the reason you run out of memory?

As for memory usage, it doesn't use more than around 4gb with the "Meta-Llama-3-8B-Instruct-Q4_0.gguf" checkpoint. Maybe it's unclear but it should be this specific checkpoint from the llama3 java repo as it's a "pure q4_0" quant, and not mixed.

I don't support quants other than q4_0 right now, but I've been wanting to add support.

**Comment by CapsAdmin** [comment]
I forgot I'm using pthreads on cpu, so I guess that backend won't work. Though it might be easy to add a windows version.

**Comment by JohnClaw** [comment]
> I forgot I'm using pthreads on cpu, so I guess that backend won't work. Though it might be easy to add a windows version.

Did i got you right that only cuda works on Windows?

**Comment by JohnClaw** [comment]
> Though it might be easy to add a windows version.

Please, make lua/pthreads cpu backends work on Windows. My only pc is a laptop without nvidia gpu. It only has cpu Ryzen 7 4700u and igpu AMD Vega 7 which doesn't support cuda.

**Comment by JohnClaw** [comment]
> Though it might be easy to add a windows version.

If you need pre-built dlls/libs/includes for pthreads on Windows then here they are: https://github.com/wangzhaode/mnn-llm/blob/master/resource/win_pthreads.zip

**Comment by CapsAdmin** [comment]
I think it's easier to just native windows threads in place. There isn't that much code behind the implementation.

**Comment by JohnClaw** [comment]
> I think it's easier to just native windows threads in place. There isn't that much code behind the implementation.

I'm not a coder/geek/scientist and not a native English speaker so for me this task is impossible.

**Comment by JohnClaw** [comment]
> Maybe the 32bit gc is the reason you run out of memory?

I don't use gcc to compile luajit source, i use .bat file from luajit repo. This .bat file uses compiler from MS Visual Studio 2022. So i don't know whether luajit.exe is 32 or 64 bit. When i try to compile luajit using gcc from w64devkit 1.21.0 i get error: 

```
~ $ cd c:\\ljt0
C:/ljt0 $ cd luajit
C:/ljt0/luajit $ cd src
C:/ljt0/luajit/src $ make
VERSION   luajit.h
c:/dvkt21/bin/sh: syntax error: unexpected "(" (expecting "then")
make: *** [Makefile:661: luajit.h] Error 2
```

I attached luajit files which i compiled with ms visual studio developer command prompt.
[lua_binaries.zip](https://github.com/user-attachments/files/18247758/lua_binaries.zip)

**Comment by JohnClaw** [comment]
> I've fixed both of those errors now.

Your fix produces new error:

```
luajit: .\debug\get_time.lua:34: attempt to index global 'system' (a nil value)
stack traceback:
        .\debug\get_time.lua:34: in main chunk
        [C]: in function 'require'
        llama.lua:4: in main chunk
        [C]: at 0x00aa3200
```

**Comment by JohnClaw** [comment]
Deepseek helped me to figure out how to build 32bit and 64bit luajit exe and lua dll. "He" also helped me to modify cpu_pthreads.lua to work on windows. So i tried luajit 32bit/luajit 64bit with pthreads 32bit/64bit dll-s but in both cases i got already known error - luajit: not enough memory. I also tried luajit 32bit/luajit 64bit with lua backend but got the same error again. I attached modified cpu_pthreads.lua.
[cpu_pthreads_modified.zip](https://github.com/user-attachments/files/18249218/cpu_pthreads_modified.zip)

**Comment by CapsAdmin** [comment]
I'm testing it now in a vm. I'm also getting the same error, but so far it seems like a really odd problem and I think maybe some of my bindings some where are wrong. It happens somewhere when loading the metadata for the gguf model.

Windows threads should be easy to get working as I just really use 2 functions.

**Comment by CapsAdmin** [comment]
Should work now.

**Comment by JohnClaw** [comment]
> Should work now.

It works! Thank you very much.
